name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/add-github-actions
    paths:
      - 'index.html'

  pull_request:
    branches:
      - main
      - feature/add-github-actions
    paths:
      - 'index.html'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4